<?xml version="1.0" encoding="utf-8"?><Database Name="capstone" Class="CapstoneDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-C3KP7HM\SQLEXPRESS;Initial Catalog=capstone;Integrated Security=True" SettingsObjectName="DB_UnitTestingConsole.Properties.Settings" SettingsPropertyName="capstoneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Choices" Member="Choices">
    <Type Name="Choice">
      <Column Name="EncID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NextEID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Question_Choice" Member="Question" ThisKey="QuestionID" OtherKey="ID" Type="Question" IsForeignKey="true" />
      <Association Name="Encounter_Choice" Member="Encounter" ThisKey="EncID" OtherKey="EncounterID" Type="Encounter" IsForeignKey="true" />
      <Association Name="Encounter_Choice1" Member="Encounter1" ThisKey="NextEID" OtherKey="EncounterID" Type="Encounter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="EncID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Question_Choice" Member="Choices" ThisKey="ID" OtherKey="QuestionID" Type="Choice" />
      <Association Name="Encounter_Question" Member="Encounter" ThisKey="EncID" OtherKey="EncounterID" Type="Encounter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Encounter" Member="Encounters">
    <Type Name="Encounter">
      <Column Name="EncounterID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EncounterTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Encounter_Choice" Member="Choices" ThisKey="EncounterID" OtherKey="EncID" Type="Choice" />
      <Association Name="Encounter_Choice1" Member="Choices1" ThisKey="EncounterID" OtherKey="NextEID" Type="Choice" />
      <Association Name="Encounter_Question" Member="Questions" ThisKey="EncounterID" OtherKey="EncID" Type="Question" />
      <Association Name="EncounterType_Encounter" Member="EncounterType" ThisKey="EncounterTypeID" OtherKey="ID" Type="EncounterType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EncounterType" Member="EncounterTypes">
    <Type Name="EncounterType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="EncounterType_Encounter" Member="Encounters" ThisKey="ID" OtherKey="EncounterTypeID" Type="Encounter" />
    </Type>
  </Table>
</Database>